{"protocolVersion":"0.1.1","runnerVersion":null,"pid":20257,"type":"start","time":0}
{"suite":{"id":0,"platform":"vm","path":"/Users/condelab/AndroidStudioProjects/SonalysisRevamp/test/widget_test.dart"},"type":"suite","time":0}
{"test":{"id":1,"name":"loading /Users/condelab/AndroidStudioProjects/SonalysisRevamp/test/widget_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1}
{"count":1,"time":9,"type":"allSuites"}

[{"event":"test.startedProcess","params":{"observatoryUri":"http://127.0.0.1:50115/E_RMlp1leeA=/"}}]
{"testID":1,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":26753}
{"group":{"id":2,"suiteID":0,"parentID":null,"name":"","metadata":{"skip":false,"skipReason":null},"testCount":1,"line":null,"column":null,"url":null},"type":"group","time":26758}
{"test":{"id":3,"name":"Counter increments smoke test","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":153,"column":5,"url":"package:flutter_test/src/widget_tester.dart","root_line":14,"root_column":3,"root_url":"file:///Users/condelab/AndroidStudioProjects/SonalysisRevamp/test/widget_test.dart"},"type":"testStart","time":26759}
{"testID":3,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════\nThe following _CastError was thrown building AdaptiveTheme(dirty, state: _AdaptiveThemeState#50b44):\nNull check operator used on a null value\n\nThe relevant error-causing widget was:\n  AdaptiveTheme\n  AdaptiveTheme:file:///Users/condelab/AndroidStudioProjects/SonalysisRevamp/lib/main.dart:369:16\n\nWhen the exception was thrown, this was the stack:\n#0      BuildContextEasyLocalizationExtension.localizationDelegates (package:easy_localization/src/public_ext.dart:148:32)\n#1      _MyAppState.build.<anonymous closure>.<anonymous closure> (package:sonalysis/main.dart:382:47)\n#2      _AdaptiveThemeState.build (package:adaptive_theme/src/adaptive_theme.dart:213:21)\n#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919:27)\n#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)\n#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)\n#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)\n#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)\n#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4968:11)\n#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)\n...     Normal element mounting (29 frames)\n#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)\n#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3545:20)\n#40     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1202:16)\n#41     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1179:5)\n#42     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1193:7)\n#43     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)\n#44     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)\n#45     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1183:19)\n#46     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)\n#47     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)\n#48     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)\n#49     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1050:9)\n#52     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\n#53     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1037:27)\n#54     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:548:22)\n#57     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\n#58     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:545:27)\n#59     main.<anonymous closure> (file:///Users/condelab/AndroidStudioProjects/SonalysisRevamp/test/widget_test.dart:16:18)\n#60     main.<anonymous closure> (file:///Users/condelab/AndroidStudioProjects/SonalysisRevamp/test/widget_test.dart:14:48)\n#61     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)\n<asynchronous suspension>\n<asynchronous suspension>\n(elided 5 frames from dart:async and package:stack_trace)\n\n════════════════════════════════════════════════════════════════════════════════════════════════════","type":"print","time":27300}
{"testID":3,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════\nThe following TestFailure was thrown running a test:\nExpected: exactly one matching node in the widget tree\n  Actual: _TextFinder:<zero widgets with text \"0\" (ignoring offstage widgets)>\n   Which: means none were found but one was expected\n\nWhen the exception was thrown, this was the stack:\n#4      main.<anonymous closure> (file:///Users/condelab/AndroidStudioProjects/SonalysisRevamp/test/widget_test.dart:19:5)\n<asynchronous suspension>\n<asynchronous suspension>\n(elided one frame from package:stack_trace)\n\nThis was caught by the test expectation on the following line:\n  file:///Users/condelab/AndroidStudioProjects/SonalysisRevamp/test/widget_test.dart line 19\nThe test description was:\n  Counter increments smoke test\n════════════════════════════════════════════════════════════════════════════════════════════════════","type":"print","time":27308}
{"testID":3,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════\nThe following message was thrown:\nMultiple exceptions (2) were detected during the running of the current test, and at least one was\nunexpected.\n════════════════════════════════════════════════════════════════════════════════════════════════════","type":"print","time":27309}
{"testID":3,"error":"Test failed. See exception logs above.\nThe test description was: Counter increments smoke test","stackTrace":"","isFailure":false,"type":"error","time":27314}
{"testID":3,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":27320}
{"success":false,"type":"done","time":33379}
